# Generated by Django 5.2.5 on 2025-09-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='tenant',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='payments',
            name='invoice_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_receipt_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paid_at',
            field=models.DateField(default=None),
        ),
        migrations.DeleteModel(
            name='Bills',
        ),
    ]
