# Generated by Django 5.2.5 on 2025-09-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_tenant_payments_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='account',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_utr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
