# Generated by Django 5.2.5 on 2025-09-14 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payments_account_payments_payment_utr_and_more'),
        ('users', '0004_account_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.account'),
        ),
    ]
