# Generated by Django 5.2.5 on 2025-09-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payments_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='paid_at',
            new_name='marked_paid_at',
        ),
    ]
