# Generated by Django 5.2.5 on 2025-09-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_paid_at_payments_marked_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='marked_paid_at',
            field=models.DateTimeField(default=None),
        ),
    ]
