# Generated by Django 5.2.5 on 2025-08-30 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField(unique=True)),
                ('occupants', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='tenants.property')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='TenantsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('pending', 'Pending'), ('partial', 'Partial'), ('overdue', 'Overdue')], default='unpaid', max_length=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lightbill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_reading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('waterbill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants_data', to='users.account')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='tenants.room')),
            ],
            options={
                'verbose_name': 'Tenants Data',
                'verbose_name_plural': 'Tenants Data',
                'db_table': 'tenants_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
