# Generated by Django 5.2.5 on 2025-09-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='TenantsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('not_paid', 'Not Paid'), ('not_reviewed', 'Not Reviewed'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='not_paid', max_length=12)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lightbill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_tenant_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_month', models.DateTimeField(auto_now_add=True)),
                ('invoice_url', models.URLField(blank=True, max_length=500, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tenants Data',
                'verbose_name_plural': 'Tenants Data',
                'db_table': 'tenants_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(blank=True, null=True)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(choices=[('id_proof', 'ID Proof'), ('driving_license', 'Driving License'), ('aadhar_card', 'Aadhar Card'), ('pan_card', 'Pan Card'), ('lease_agreement', 'Lease Agreement'), ('meter_reading', 'Meter Reading'), ('light_bill', 'Light Bill'), ('water_bill', 'Water Bill'), ('maintenance', 'Maintenance'), ('payment_receipt', 'Payment Receipt'), ('invoice_bill', 'Invoice Bill'), ('other', 'Other')], max_length=20)),
                ('unit_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenants Files',
                'verbose_name_plural': 'Tenants Files',
                'db_table': 'tenants_files',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField(unique=True)),
                ('active_tenants', models.IntegerField(default=0)),
                ('max_occupants', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='tenants.property')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['room_number'],
            },
        ),
    ]
