# Generated by Django 5.2.5 on 2025-09-05 10:38

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0002_account_id_alter_account_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('file_type', models.CharField(choices=[('id_proof', 'ID Proof'), ('driving_license', 'Driving License'), ('aadhar_card', 'Aadhar Card'), ('pan_card', 'Pan Card'), ('lease_agreement', 'Lease Agreement'), ('meter_reading', 'Meter Reading'), ('light_bill', 'Light Bill'), ('water_bill', 'Water Bill'), ('Maintenance', 'Maintenance'), ('payment_receipt', 'Payment Receipt'), ('other', 'Other')], max_length=20)),
                ('unit_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants_files', to='users.account')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants_files', to='tenants.room')),
            ],
            options={
                'verbose_name': 'Tenants Files',
                'verbose_name_plural': 'Tenants Files',
                'db_table': 'tenants_files',
            },
        ),
    ]
