# Generated by Django 5.2.5 on 2025-09-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsdata',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants_data', to='users.account'),
        ),
        migrations.AddField(
            model_name='tenantsdata',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='tenants.room'),
        ),
        migrations.AddField(
            model_name='tenantsfiles',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants_files', to='users.account'),
        ),
        migrations.AddField(
            model_name='tenantsfiles',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants_files', to='tenants.room'),
        ),
    ]
