# Generated by Django 5.2.5 on 2025-09-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantsfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsfiles',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
