# Generated by Django 5.2.5 on 2025-09-08 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantsfiles_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantsdata',
            old_name='rent_status',
            new_name='payment_status',
        ),
        migrations.RemoveField(
            model_name='tenantsdata',
            name='unit_reading',
        ),
        migrations.RemoveField(
            model_name='tenantsdata',
            name='waterbill_amount',
        ),
        migrations.AddField(
            model_name='tenantsdata',
            name='invoice_month',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
