# Generated by Django 5.2.5 on 2025-09-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_rename_rent_status_tenantsdata_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantsdata',
            name='deposit_amount',
        ),
    ]
