# Generated by Django 5.2.5 on 2025-09-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_remove_tenantsdata_deposit_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='occupants',
            new_name='max_occupants',
        ),
        migrations.AddField(
            model_name='room',
            name='active_tenants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenantsdata',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid'), ('partial', 'Partial'), ('overdue', 'Overdue')], default='unpaid', max_length=10),
        ),
    ]
