# Generated by Django 5.2.5 on 2025-09-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_rename_occupants_room_max_occupants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantsfiles',
            name='file',
        ),
        migrations.AddField(
            model_name='tenantsfiles',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
