# Generated by Django 5.2.5 on 2025-09-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_remove_tenantsfiles_file_tenantsfiles_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsdata',
            name='per_tenant_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tenantsdata',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
