# Generated by Django 5.2.5 on 2025-09-13 07:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenantsdata_per_tenant_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsfiles',
            name='file_type',
            field=models.CharField(choices=[('id_proof', 'ID Proof'), ('driving_license', 'Driving License'), ('aadhar_card', 'Aadhar Card'), ('pan_card', 'Pan Card'), ('lease_agreement', 'Lease Agreement'), ('meter_reading', 'Meter Reading'), ('light_bill', 'Light Bill'), ('water_bill', 'Water Bill'), ('maintenance', 'Maintenance'), ('payment_receipt', 'Payment Receipt'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantsfiles',
            name='file_url',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
