# Generated by Django 5.2.5 on 2025-09-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_tenantsfiles_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsfiles',
            name='download_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantsfiles',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
