# Generated by Django 5.2.5 on 2025-09-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenantsfiles_download_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsfiles',
            name='file_type',
            field=models.CharField(choices=[('id_proof', 'ID Proof'), ('driving_license', 'Driving License'), ('aadhar_card', 'Aadhar Card'), ('pan_card', 'Pan Card'), ('lease_agreement', 'Lease Agreement'), ('meter_reading', 'Meter Reading'), ('light_bill', 'Light Bill'), ('water_bill', 'Water Bill'), ('maintenance', 'Maintenance'), ('payment_receipt', 'Payment Receipt'), ('invoice_bill', 'Invoice Bill'), ('other', 'Other')], max_length=20),
        ),
    ]
