# Generated by Django 5.2.5 on 2025-09-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_alter_tenantsfiles_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsdata',
            name='invoice_id',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tenantsdata',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid'), ('partial', 'Partial'), ('overdue', 'Overdue')], default='not_paid', max_length=10),
        ),
    ]
