# Generated by Django 5.2.5 on 2025-09-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenantsdata_invoice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantsdata',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='tenantsdata',
            name='invoice_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
