# Generated by Django 5.2.5 on 2025-09-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_remove_tenantsdata_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsdata',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
