# Generated by Django 5.2.5 on 2025-09-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
